[package]
name = "jogo_adivinhacao"
version = "0.1.0"
authors = ["Marcelo Junior <marcelo.jr63@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.3"
